// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEoztJ8VJEN5ATQ38NVQmhUgPEfsAWm6s',
    appId: '1:392583779889:web:8dfc76175519c1be46a710',
    messagingSenderId: '392583779889',
    projectId: 'inventory-dcb86',
    authDomain: 'inventory-dcb86.firebaseapp.com',
    storageBucket: 'inventory-dcb86.firebasestorage.app',
    measurementId: 'G-4N4Y8EM68G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChOIYkRI5VcA9Jlwt4cFkykMwkhAmEp3Y',
    appId: '1:392583779889:android:0c861f5cbbdc9acf46a710',
    messagingSenderId: '392583779889',
    projectId: 'inventory-dcb86',
    storageBucket: 'inventory-dcb86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz5MF9_yE6CNkHdg9OXsrJ4aQjUtU7nMQ',
    appId: '1:392583779889:ios:140438ec4f7fc47446a710',
    messagingSenderId: '392583779889',
    projectId: 'inventory-dcb86',
    storageBucket: 'inventory-dcb86.firebasestorage.app',
    iosBundleId: 'com.example.assingement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz5MF9_yE6CNkHdg9OXsrJ4aQjUtU7nMQ',
    appId: '1:392583779889:ios:140438ec4f7fc47446a710',
    messagingSenderId: '392583779889',
    projectId: 'inventory-dcb86',
    storageBucket: 'inventory-dcb86.firebasestorage.app',
    iosBundleId: 'com.example.assingement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEoztJ8VJEN5ATQ38NVQmhUgPEfsAWm6s',
    appId: '1:392583779889:web:c0084824d52b434846a710',
    messagingSenderId: '392583779889',
    projectId: 'inventory-dcb86',
    authDomain: 'inventory-dcb86.firebaseapp.com',
    storageBucket: 'inventory-dcb86.firebasestorage.app',
    measurementId: 'G-FJCPGH7QLL',
  );
}
